version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: outliant_container
    command: mongod --auth
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_NON_ROOT_USERNAME=${MONGO_NON_ROOT_USERNAME}
      - MONGO_NON_ROOT_PASSWORD=${MONGO_NON_ROOT_PASSWORD}
    volumes:
      - ./database/home/mongodb:/home/mongodb
      - mongodbdata:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017-27019:27017-27019'
volumes:
  mongodbdata:
    driver: local
